/* Replace with your SQL commands */
DROP TABLE IF EXISTS Orders CASCADE;
DROP TABLE IF EXISTS Bills CASCADE;
DROP TABLE IF EXISTS ShipmentStatus CASCADE;
DROP TABLE IF EXISTS ShoppingCartProducts CASCADE;
DROP TABLE IF EXISTS ShoppingCarts CASCADE;
DROP TABLE IF EXISTS ShipmentStatusCodes CASCADE;
