const ErrorType = {
  API_ERROR: 'API_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  REQUEST_BODY_ERROR: 'REQUEST_BODY_ERROR',
  AUTH_ERROR: 'AUTHENTICATION_ERROR'
}

export default ErrorType
